/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * simulate payment request object
 * @export
 * @interface SimulateRequest
 */
export interface SimulateRequest {
    /**
     * Entity type should be PAYMENTS or SUBS_PAYMENTS only.
     * @type {string}
     * @memberof SimulateRequest
     */
    'entity': ENTITY;
    /**
     * If the entity type is PAYMENTS, the entity_id will be the transactionId. If the entity type is SUBS_PAYMENTS, the entity_id will be the merchantTxnId
     * @type {string}
     * @memberof SimulateRequest
     */
    'entity_id': string;
    /**
     * 
     * @type {EntitySimulationRequest}
     * @memberof SimulateRequest
     */
    'entity_simulation': EntitySimulationRequest;
}

export const ENTITY = {
    PAYMENTS: "PAYMENTS",
    SUBS_PAYMENTS: "SUBS_PAYMENTS",
    UNKNOWN_DEFAULT_OPEN_API: "11184809"
} as const;

export type ENTITY = typeof ENTITY[keyof typeof ENTITY];

