/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2026-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"fmt"
	"strings"
)

var _ = fmt.Errorf

// checks if the VendorReconRequestPagination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VendorReconRequestPagination{}

// VendorReconRequestPagination The merchant can set pagination limits based on their use case. The minimum limit is 10. Pagination will fetch a set of records, and the next set of records can be generated using the cursor provided in response to the first request for all reconciliation APIs.
type VendorReconRequestPagination struct {
	// Set the minimum or maximum limit for the number of filtered data. Minimum value: 10, Maximum value: 100.
	Limit int32 `json:"limit"`
	// Specifies from where the next set of records should be fetched.
	Cursor *string `json:"cursor,omitempty"`
}


func (o VendorReconRequestPagination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VendorReconRequestPagination) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	toSerialize["limit"] = o.Limit
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	return toSerialize, nil
}


