/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2023-08-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"strings"
)

// checks if the BanktransferPaymentMethod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BanktransferPaymentMethod{}

// BanktransferPaymentMethod banktransfer payment method
type BanktransferPaymentMethod struct {
	Banktransfer Banktransfer `json:"banktransfer"`
}


func (o BanktransferPaymentMethod) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BanktransferPaymentMethod) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	toSerialize["banktransfer"] = o.Banktransfer
	return toSerialize, nil
}



