/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2026-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"fmt"
	"strings"
)

var _ = fmt.Errorf

// checks if the PayOrderAuthorizeOnlyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayOrderAuthorizeOnlyRequest{}

// PayOrderAuthorizeOnlyRequest Complete object for the authorize only api that uses authorization data object
type PayOrderAuthorizeOnlyRequest struct {
	PaymentSessionId string `json:"payment_session_id"`
	AuthorizationData PayOrderAuthorizeOnlyRequestAuthorizationData `json:"authorization_data"`
}


func (o PayOrderAuthorizeOnlyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayOrderAuthorizeOnlyRequest) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	toSerialize["payment_session_id"] = o.PaymentSessionId
	toSerialize["authorization_data"] = o.AuthorizationData
	return toSerialize, nil
}


