/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2023-08-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"strings"
)

// checks if the DisputeEvidence type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisputeEvidence{}

// DisputeEvidence struct for DisputeEvidence
type DisputeEvidence struct {
	// []Evidence
}


func (o DisputeEvidence) MarshalJSON() ([]byte, error) {
	return []byte{}, err
}

func (o DisputeEvidence) ToMap() (map[string]interface{}, error) {
	return []byte{}, err
}



