/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2022-09-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
)

// checks if the AuthorizationInPaymentsEntity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizationInPaymentsEntity{}

// AuthorizationInPaymentsEntity If preauth enabled for account you will get this body
type AuthorizationInPaymentsEntity struct {
	// One of CAPTURE or VOID
	Action *string `json:"action,omitempty"`
	// One of SUCCESS or PENDING
	Status *string `json:"status,omitempty"`
	// The captured amount for this authorization request
	CapturedAmount *float32 `json:"captured_amount,omitempty"`
	// Start time of this authorization hold (only for UPI)
	StartTime *string `json:"start_time,omitempty"`
	// End time of this authorization hold (only for UPI)
	EndTime *string `json:"end_time,omitempty"`
	// Approve by time as passed in the authorization request (only for UPI)
	ApproveBy *string `json:"approve_by,omitempty"`
	// CAPTURE or VOID reference number based on action 
	ActionReference *string `json:"action_reference,omitempty"`
	// Time of action (CAPTURE or VOID)
	ActionTime *string `json:"action_time,omitempty"`
}

// NewAuthorizationInPaymentsEntity instantiates a new AuthorizationInPaymentsEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizationInPaymentsEntity() *AuthorizationInPaymentsEntity {
	this := AuthorizationInPaymentsEntity{}
	return &this
}

// NewAuthorizationInPaymentsEntityWithDefaults instantiates a new AuthorizationInPaymentsEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizationInPaymentsEntityWithDefaults() *AuthorizationInPaymentsEntity {
	this := AuthorizationInPaymentsEntity{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *AuthorizationInPaymentsEntity) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationInPaymentsEntity) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *AuthorizationInPaymentsEntity) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *AuthorizationInPaymentsEntity) SetAction(v string) {
	o.Action = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AuthorizationInPaymentsEntity) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationInPaymentsEntity) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AuthorizationInPaymentsEntity) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AuthorizationInPaymentsEntity) SetStatus(v string) {
	o.Status = &v
}

// GetCapturedAmount returns the CapturedAmount field value if set, zero value otherwise.
func (o *AuthorizationInPaymentsEntity) GetCapturedAmount() float32 {
	if o == nil || IsNil(o.CapturedAmount) {
		var ret float32
		return ret
	}
	return *o.CapturedAmount
}

// GetCapturedAmountOk returns a tuple with the CapturedAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationInPaymentsEntity) GetCapturedAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.CapturedAmount) {
		return nil, false
	}
	return o.CapturedAmount, true
}

// HasCapturedAmount returns a boolean if a field has been set.
func (o *AuthorizationInPaymentsEntity) HasCapturedAmount() bool {
	if o != nil && !IsNil(o.CapturedAmount) {
		return true
	}

	return false
}

// SetCapturedAmount gets a reference to the given float32 and assigns it to the CapturedAmount field.
func (o *AuthorizationInPaymentsEntity) SetCapturedAmount(v float32) {
	o.CapturedAmount = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *AuthorizationInPaymentsEntity) GetStartTime() string {
	if o == nil || IsNil(o.StartTime) {
		var ret string
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationInPaymentsEntity) GetStartTimeOk() (*string, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *AuthorizationInPaymentsEntity) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given string and assigns it to the StartTime field.
func (o *AuthorizationInPaymentsEntity) SetStartTime(v string) {
	o.StartTime = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *AuthorizationInPaymentsEntity) GetEndTime() string {
	if o == nil || IsNil(o.EndTime) {
		var ret string
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationInPaymentsEntity) GetEndTimeOk() (*string, bool) {
	if o == nil || IsNil(o.EndTime) {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *AuthorizationInPaymentsEntity) HasEndTime() bool {
	if o != nil && !IsNil(o.EndTime) {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given string and assigns it to the EndTime field.
func (o *AuthorizationInPaymentsEntity) SetEndTime(v string) {
	o.EndTime = &v
}

// GetApproveBy returns the ApproveBy field value if set, zero value otherwise.
func (o *AuthorizationInPaymentsEntity) GetApproveBy() string {
	if o == nil || IsNil(o.ApproveBy) {
		var ret string
		return ret
	}
	return *o.ApproveBy
}

// GetApproveByOk returns a tuple with the ApproveBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationInPaymentsEntity) GetApproveByOk() (*string, bool) {
	if o == nil || IsNil(o.ApproveBy) {
		return nil, false
	}
	return o.ApproveBy, true
}

// HasApproveBy returns a boolean if a field has been set.
func (o *AuthorizationInPaymentsEntity) HasApproveBy() bool {
	if o != nil && !IsNil(o.ApproveBy) {
		return true
	}

	return false
}

// SetApproveBy gets a reference to the given string and assigns it to the ApproveBy field.
func (o *AuthorizationInPaymentsEntity) SetApproveBy(v string) {
	o.ApproveBy = &v
}

// GetActionReference returns the ActionReference field value if set, zero value otherwise.
func (o *AuthorizationInPaymentsEntity) GetActionReference() string {
	if o == nil || IsNil(o.ActionReference) {
		var ret string
		return ret
	}
	return *o.ActionReference
}

// GetActionReferenceOk returns a tuple with the ActionReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationInPaymentsEntity) GetActionReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.ActionReference) {
		return nil, false
	}
	return o.ActionReference, true
}

// HasActionReference returns a boolean if a field has been set.
func (o *AuthorizationInPaymentsEntity) HasActionReference() bool {
	if o != nil && !IsNil(o.ActionReference) {
		return true
	}

	return false
}

// SetActionReference gets a reference to the given string and assigns it to the ActionReference field.
func (o *AuthorizationInPaymentsEntity) SetActionReference(v string) {
	o.ActionReference = &v
}

// GetActionTime returns the ActionTime field value if set, zero value otherwise.
func (o *AuthorizationInPaymentsEntity) GetActionTime() string {
	if o == nil || IsNil(o.ActionTime) {
		var ret string
		return ret
	}
	return *o.ActionTime
}

// GetActionTimeOk returns a tuple with the ActionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationInPaymentsEntity) GetActionTimeOk() (*string, bool) {
	if o == nil || IsNil(o.ActionTime) {
		return nil, false
	}
	return o.ActionTime, true
}

// HasActionTime returns a boolean if a field has been set.
func (o *AuthorizationInPaymentsEntity) HasActionTime() bool {
	if o != nil && !IsNil(o.ActionTime) {
		return true
	}

	return false
}

// SetActionTime gets a reference to the given string and assigns it to the ActionTime field.
func (o *AuthorizationInPaymentsEntity) SetActionTime(v string) {
	o.ActionTime = &v
}

func (o AuthorizationInPaymentsEntity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizationInPaymentsEntity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CapturedAmount) {
		toSerialize["captured_amount"] = o.CapturedAmount
	}
	if !IsNil(o.StartTime) {
		toSerialize["start_time"] = o.StartTime
	}
	if !IsNil(o.EndTime) {
		toSerialize["end_time"] = o.EndTime
	}
	if !IsNil(o.ApproveBy) {
		toSerialize["approve_by"] = o.ApproveBy
	}
	if !IsNil(o.ActionReference) {
		toSerialize["action_reference"] = o.ActionReference
	}
	if !IsNil(o.ActionTime) {
		toSerialize["action_time"] = o.ActionTime
	}
	return toSerialize, nil
}

type NullableAuthorizationInPaymentsEntity struct {
	value *AuthorizationInPaymentsEntity
	isSet bool
}

func (v NullableAuthorizationInPaymentsEntity) Get() *AuthorizationInPaymentsEntity {
	return v.value
}

func (v *NullableAuthorizationInPaymentsEntity) Set(val *AuthorizationInPaymentsEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizationInPaymentsEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizationInPaymentsEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizationInPaymentsEntity(val *AuthorizationInPaymentsEntity) *NullableAuthorizationInPaymentsEntity {
	return &NullableAuthorizationInPaymentsEntity{value: val, isSet: true}
}

func (v NullableAuthorizationInPaymentsEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizationInPaymentsEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


