/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * the data object pay api
 * @export
 * @interface OrderPayData
 */
export interface OrderPayData {
    /**
     * 
     * @type {string}
     * @memberof OrderPayData
     */
    'url'?: string;
    /**
     * 
     * @type {map[string]interface{}}
     * @memberof OrderPayData
     */
    'payload'?: map[string]interface{};
    /**
     * 
     * @type {string}
     * @memberof OrderPayData
     */
    'content_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderPayData
     */
    'method'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderPayData
     */
    'redirect_to_bank'?: string;
}
