/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2025-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"strings"
)

// checks if the UpdateTerminalRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTerminalRequest{}

// UpdateTerminalRequest Request body to update terminal details.
type UpdateTerminalRequest struct {
	// Mention the updated email ID of the terminal.
	TerminalEmail *string `json:"terminal_email,omitempty"`
	// Terminal phone number to be updated.
	TerminalPhoneNo *string `json:"terminal_phone_no,omitempty"`
	TerminalMeta *UpdateTerminalRequestTerminalMeta `json:"terminal_meta,omitempty"`
	// Mention the terminal type to be updated. Possible values - AGENT, STOREFRONT.
	TerminalType string `json:"terminal_type"`
}


func (o UpdateTerminalRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTerminalRequest) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TerminalEmail) {
		toSerialize["terminal_email"] = o.TerminalEmail
	}
	if !IsNil(o.TerminalPhoneNo) {
		toSerialize["terminal_phone_no"] = o.TerminalPhoneNo
	}
	if !IsNil(o.TerminalMeta) {
		toSerialize["terminal_meta"] = o.TerminalMeta
	}
	toSerialize["terminal_type"] = o.TerminalType
	return toSerialize, nil
}



