/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2025-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"fmt"
	"strings"
)

var _ = fmt.Errorf

// checks if the SoundboxVpaEntity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SoundboxVpaEntity{}

// SoundboxVpaEntity soundbox response object
type SoundboxVpaEntity struct {
	Vpa *string `json:"vpa,omitempty"`
	CfTerminalId *string `json:"cf_terminal_id,omitempty"`
	DeviceSerialNo *string `json:"device_serial_no,omitempty"`
	MerchantName *string `json:"merchant_name,omitempty"`
	Language *string `json:"language,omitempty"`
}


func (o SoundboxVpaEntity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SoundboxVpaEntity) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Vpa) {
		toSerialize["vpa"] = o.Vpa
	}
	if !IsNil(o.CfTerminalId) {
		toSerialize["cf_terminal_id"] = o.CfTerminalId
	}
	if !IsNil(o.DeviceSerialNo) {
		toSerialize["device_serial_no"] = o.DeviceSerialNo
	}
	if !IsNil(o.MerchantName) {
		toSerialize["merchant_name"] = o.MerchantName
	}
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	return toSerialize, nil
}


