/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2022-09-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"strings"
)

// checks if the PaymentMethodCardEMIInPaymentsEntityEmiEmiDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentMethodCardEMIInPaymentsEntityEmiEmiDetails{}

// PaymentMethodCardEMIInPaymentsEntityEmiEmiDetails struct for PaymentMethodCardEMIInPaymentsEntityEmiEmiDetails
type PaymentMethodCardEMIInPaymentsEntityEmiEmiDetails struct {
	EmiAmount *float32 `json:"emi_amount,omitempty"`
	EmiTenure *float32 `json:"emi_tenure,omitempty"`
	EmiInterest *float32 `json:"emi_interest,omitempty"`
}


func (o PaymentMethodCardEMIInPaymentsEntityEmiEmiDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentMethodCardEMIInPaymentsEntityEmiEmiDetails) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EmiAmount) {
		toSerialize["emi_amount"] = o.EmiAmount
	}
	if !IsNil(o.EmiTenure) {
		toSerialize["emi_tenure"] = o.EmiTenure
	}
	if !IsNil(o.EmiInterest) {
		toSerialize["emi_interest"] = o.EmiInterest
	}
	return toSerialize, nil
}



