/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * terminal payment entity full object
 * @export
 * @interface TerminalPaymentEntity
 */
export interface TerminalPaymentEntity {
    /**
     * 
     * @type {string}
     * @memberof TerminalPaymentEntity
     */
    'cf_payment_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TerminalPaymentEntity
     */
    'order_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TerminalPaymentEntity
     */
    'entity'?: string;
    /**
     * 
     * @type {ErrorDetailsInPaymentsEntity}
     * @memberof TerminalPaymentEntity
     */
    'error_details'?: ErrorDetailsInPaymentsEntity;
    /**
     * 
     * @type {bool}
     * @memberof TerminalPaymentEntity
     */
    'is_captured'?: bool;
    /**
     * Order amount can be different from payment amount if you collect service fee from the customer
     * @type {float32}
     * @memberof TerminalPaymentEntity
     */
    'order_amount'?: float32;
    /**
     * Type of payment group. One of ['prepaid_card', 'upi_ppi_offline', 'cash', 'upi_credit_card', 'paypal', 'net_banking', 'cardless_emi', 'credit_card', 'bank_transfer', 'pay_later', 'debit_card_emi', 'debit_card', 'wallet', 'upi_ppi', 'upi', 'credit_card_emi']
     * @type {string}
     * @memberof TerminalPaymentEntity
     */
    'payment_group'?: string;
    /**
     * 
     * @type {string}
     * @memberof TerminalPaymentEntity
     */
    'payment_currency'?: string;
    /**
     * 
     * @type {float32}
     * @memberof TerminalPaymentEntity
     */
    'payment_amount'?: float32;
    /**
     * This is the time when the payment was initiated
     * @type {string}
     * @memberof TerminalPaymentEntity
     */
    'payment_time'?: string;
    /**
     * This is the time when the payment reaches its terminal state
     * @type {string}
     * @memberof TerminalPaymentEntity
     */
    'payment_completion_time'?: string;
    /**
     * The transaction status can be one of  [\"SUCCESS\", \"NOT_ATTEMPTED\", \"FAILED\", \"USER_DROPPED\", \"VOID\", \"CANCELLED\", \"PENDING\"]
     * @type {string}
     * @memberof TerminalPaymentEntity
     */
    'payment_status'?: PAYMENT_STATUS;
    /**
     * 
     * @type {string}
     * @memberof TerminalPaymentEntity
     */
    'payment_message'?: string;
    /**
     * 
     * @type {string}
     * @memberof TerminalPaymentEntity
     */
    'bank_reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof TerminalPaymentEntity
     */
    'auth_id'?: string;
    /**
     * 
     * @type {AuthorizationInPaymentsEntity}
     * @memberof TerminalPaymentEntity
     */
    'authorization'?: AuthorizationInPaymentsEntity;
    /**
     * 
     * @type {CustomerDetails}
     * @memberof TerminalPaymentEntity
     */
    'customer_details'?: CustomerDetails;
    /**
     * 
     * @type {PaymentEntityPaymentMethod}
     * @memberof TerminalPaymentEntity
     */
    'payment_method'?: PaymentEntityPaymentMethod;
    /**
     * 
     * @type {PaymentGatewayDetails}
     * @memberof TerminalPaymentEntity
     */
    'payment_gateway_details'?: PaymentGatewayDetails;
}

export const PAYMENT_STATUS = {
    SUCCESS: "SUCCESS",
    NOT_ATTEMPTED: "NOT_ATTEMPTED",
    FAILED: "FAILED",
    USER_DROPPED: "USER_DROPPED",
    VOID: "VOID",
    CANCELLED: "CANCELLED",
    PENDING: "PENDING",
    UNKNOWN_DEFAULT_OPEN_API: "11184809"
} as const;

export type PAYMENT_STATUS = typeof PAYMENT_STATUS[keyof typeof PAYMENT_STATUS];

