/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Cashback detail boject
 * @export
 * @interface CashbackDetails
 */
export interface CashbackDetails {
    /**
     * Type of discount
     * @type {string}
     * @memberof CashbackDetails
     */
    'cashback_type': CASHBACK_TYPE;
    /**
     * Value of Discount.
     * @type {float32}
     * @memberof CashbackDetails
     */
    'cashback_value': float32;
    /**
     * Maximum Value of Cashback allowed.
     * @type {float32}
     * @memberof CashbackDetails
     */
    'max_cashback_amount': float32;
}

export const CASHBACK_TYPE = {
    FLAT: "flat",
    PERCENTAGE: "percentage",
    UNKNOWN_DEFAULT_OPEN_API: "11184809"
} as const;

export type CASHBACK_TYPE = typeof CASHBACK_TYPE[keyof typeof CASHBACK_TYPE];

