/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * @type CreateSubscriptionPaymentRequestPaymentMethod
 * Payment method. Can be one of [\"upi\", \"enach\", \"pnach\", \"card\"]
 * @export
 */
export type CreateSubscriptionPaymentRequestPaymentMethod = CreateSubscriptionPaymentRequestCard | CreateSubscriptionPaymentRequestEnach | CreateSubscriptionPaymentRequestPnach | CreateSubscriptonPaymentRequestUpi;

