/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2025-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"strings"
)

// checks if the StaticSplitRequestSchemeInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StaticSplitRequestSchemeInner{}

// StaticSplitRequestSchemeInner struct for StaticSplitRequestSchemeInner
type StaticSplitRequestSchemeInner struct {
	// Specify the merchant vendor ID to create the split scheme for the payment.
	MerchantVendorId *string `json:"merchantVendorId,omitempty"`
	// Specify the percentage of amount to be split.
	Percentage *string `json:"percentage,omitempty"`
}


func (o StaticSplitRequestSchemeInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StaticSplitRequestSchemeInner) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MerchantVendorId) {
		toSerialize["merchantVendorId"] = o.MerchantVendorId
	}
	if !IsNil(o.Percentage) {
		toSerialize["percentage"] = o.Percentage
	}
	return toSerialize, nil
}



