/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2023-08-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"strings"
)

// checks if the ManageSubscriptionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManageSubscriptionRequest{}

// ManageSubscriptionRequest Request body to manage a subscription.
type ManageSubscriptionRequest struct {
	// The unique ID which was used to create subscription.
	SubscriptionId string `json:"subscription_id"`
	// Action to be performed on the subscription. Possible values - CANCEL, PAUSE, ACTIVATE, CHANGE_PLAN.
	Action string `json:"action"`
	ActionDetails *ManageSubscriptionRequestActionDetails `json:"action_details,omitempty"`
}


func (o ManageSubscriptionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManageSubscriptionRequest) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	toSerialize["subscription_id"] = o.SubscriptionId
	toSerialize["action"] = o.Action
	if !IsNil(o.ActionDetails) {
		toSerialize["action_details"] = o.ActionDetails
	}
	return toSerialize, nil
}



