/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2025-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"strings"
)

// checks if the DisputeEvidenceInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisputeEvidenceInner{}

// DisputeEvidenceInner struct for DisputeEvidenceInner
type DisputeEvidenceInner struct {
	DocumentId *int32 `json:"document_id,omitempty"`
	DocumentName *string `json:"document_name,omitempty"`
	DocumentType *string `json:"document_type,omitempty"`
}


func (o DisputeEvidenceInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisputeEvidenceInner) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DocumentId) {
		toSerialize["document_id"] = o.DocumentId
	}
	if !IsNil(o.DocumentName) {
		toSerialize["document_name"] = o.DocumentName
	}
	if !IsNil(o.DocumentType) {
		toSerialize["document_type"] = o.DocumentType
	}
	return toSerialize, nil
}



