/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2023-08-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
)

// checks if the PaymentMethodUPIInPaymentsEntity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentMethodUPIInPaymentsEntity{}

// PaymentMethodUPIInPaymentsEntity UPI payment method for pay api
type PaymentMethodUPIInPaymentsEntity struct {
	Channel string `json:"channel"`
	UpiId *string `json:"upi_id,omitempty"`
}


func (o PaymentMethodUPIInPaymentsEntity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentMethodUPIInPaymentsEntity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channel"] = o.Channel
	if !IsNil(o.UpiId) {
		toSerialize["upi_id"] = o.UpiId
	}
	return toSerialize, nil
}



