/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The request to be passed for the create subscription payment API.
 * @export
 * @interface CreateSubscriptionPaymentRequest
 */
export interface CreateSubscriptionPaymentRequest {
    /**
     * A unique ID passed by merchant for identifying the subscription.
     * @type {string}
     * @memberof CreateSubscriptionPaymentRequest
     */
    'subscription_id': string;
    /**
     * Session ID for the subscription. Required only for Auth.
     * @type {string}
     * @memberof CreateSubscriptionPaymentRequest
     */
    'subscription_session_id'?: string;
    /**
     * A unique ID passed by merchant for identifying the subscription payment.
     * @type {string}
     * @memberof CreateSubscriptionPaymentRequest
     */
    'payment_id': string;
    /**
     * The charge amount of the payment. Required in case of charge.
     * @type {float32}
     * @memberof CreateSubscriptionPaymentRequest
     */
    'payment_amount'?: float32;
    /**
     * The date on which the payment is scheduled to be processed. Required for UPI and CARD payment modes.
     * @type {string}
     * @memberof CreateSubscriptionPaymentRequest
     */
    'payment_schedule_date'?: string;
    /**
     * Payment remarks.
     * @type {string}
     * @memberof CreateSubscriptionPaymentRequest
     */
    'payment_remarks'?: string;
    /**
     * Payment type. Can be AUTH or CHARGE.
     * @type {string}
     * @memberof CreateSubscriptionPaymentRequest
     */
    'payment_type': string;
    /**
     * 
     * @type {CreateSubscriptionPaymentRequestPaymentMethod}
     * @memberof CreateSubscriptionPaymentRequest
     */
    'payment_method'?: CreateSubscriptionPaymentRequestPaymentMethod;
}
