/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2022-09-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
)

// checks if the CardEMI type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CardEMI{}

// CardEMI Payment method for card emi
type CardEMI struct {
	// The channel for card payments will always be \"link\"
	Channel string `json:"channel"`
	// Customer card number.
	CardNumber string `json:"card_number"`
	// Customer name mentioned on the card.
	CardHolderName *string `json:"card_holder_name,omitempty"`
	// Card expiry month.
	CardExpiryMm string `json:"card_expiry_mm"`
	// Card expiry year.
	CardExpiryYy string `json:"card_expiry_yy"`
	// CVV mentioned on the card.
	CardCvv string `json:"card_cvv"`
	// Card alias as returned by Cashfree Vault API
	CardAlias *string `json:"card_alias,omitempty"`
	// Card bank name, required for EMI payments. This is the bank user has selected for EMI. One of [\"hdfc, \"kotak\", \"icici\", \"rbl\", \"bob\", \"standard chartered\", \"axis\", \"au\", \"yes\", \"sbi\", \"fed\", \"hsbc\", \"citi\", \"amex\"]
	CardBankName string `json:"card_bank_name"`
	// EMI tenure selected by the user
	EmiTenure int32 `json:"emi_tenure"`
}

// NewCardEMI instantiates a new CardEMI object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardEMI(channel string, cardNumber string, cardExpiryMm string, cardExpiryYy string, cardCvv string, cardBankName string, emiTenure int32) *CardEMI {
	this := CardEMI{}
	this.Channel = channel
	this.CardNumber = cardNumber
	this.CardExpiryMm = cardExpiryMm
	this.CardExpiryYy = cardExpiryYy
	this.CardCvv = cardCvv
	this.CardBankName = cardBankName
	this.EmiTenure = emiTenure
	return &this
}

// NewCardEMIWithDefaults instantiates a new CardEMI object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardEMIWithDefaults() *CardEMI {
	this := CardEMI{}
	return &this
}

// GetChannel returns the Channel field value
func (o *CardEMI) GetChannel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *CardEMI) GetChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *CardEMI) SetChannel(v string) {
	o.Channel = v
}

// GetCardNumber returns the CardNumber field value
func (o *CardEMI) GetCardNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CardNumber
}

// GetCardNumberOk returns a tuple with the CardNumber field value
// and a boolean to check if the value has been set.
func (o *CardEMI) GetCardNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardNumber, true
}

// SetCardNumber sets field value
func (o *CardEMI) SetCardNumber(v string) {
	o.CardNumber = v
}

// GetCardHolderName returns the CardHolderName field value if set, zero value otherwise.
func (o *CardEMI) GetCardHolderName() string {
	if o == nil || IsNil(o.CardHolderName) {
		var ret string
		return ret
	}
	return *o.CardHolderName
}

// GetCardHolderNameOk returns a tuple with the CardHolderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardEMI) GetCardHolderNameOk() (*string, bool) {
	if o == nil || IsNil(o.CardHolderName) {
		return nil, false
	}
	return o.CardHolderName, true
}

// HasCardHolderName returns a boolean if a field has been set.
func (o *CardEMI) HasCardHolderName() bool {
	if o != nil && !IsNil(o.CardHolderName) {
		return true
	}

	return false
}

// SetCardHolderName gets a reference to the given string and assigns it to the CardHolderName field.
func (o *CardEMI) SetCardHolderName(v string) {
	o.CardHolderName = &v
}

// GetCardExpiryMm returns the CardExpiryMm field value
func (o *CardEMI) GetCardExpiryMm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CardExpiryMm
}

// GetCardExpiryMmOk returns a tuple with the CardExpiryMm field value
// and a boolean to check if the value has been set.
func (o *CardEMI) GetCardExpiryMmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardExpiryMm, true
}

// SetCardExpiryMm sets field value
func (o *CardEMI) SetCardExpiryMm(v string) {
	o.CardExpiryMm = v
}

// GetCardExpiryYy returns the CardExpiryYy field value
func (o *CardEMI) GetCardExpiryYy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CardExpiryYy
}

// GetCardExpiryYyOk returns a tuple with the CardExpiryYy field value
// and a boolean to check if the value has been set.
func (o *CardEMI) GetCardExpiryYyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardExpiryYy, true
}

// SetCardExpiryYy sets field value
func (o *CardEMI) SetCardExpiryYy(v string) {
	o.CardExpiryYy = v
}

// GetCardCvv returns the CardCvv field value
func (o *CardEMI) GetCardCvv() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CardCvv
}

// GetCardCvvOk returns a tuple with the CardCvv field value
// and a boolean to check if the value has been set.
func (o *CardEMI) GetCardCvvOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardCvv, true
}

// SetCardCvv sets field value
func (o *CardEMI) SetCardCvv(v string) {
	o.CardCvv = v
}

// GetCardAlias returns the CardAlias field value if set, zero value otherwise.
func (o *CardEMI) GetCardAlias() string {
	if o == nil || IsNil(o.CardAlias) {
		var ret string
		return ret
	}
	return *o.CardAlias
}

// GetCardAliasOk returns a tuple with the CardAlias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardEMI) GetCardAliasOk() (*string, bool) {
	if o == nil || IsNil(o.CardAlias) {
		return nil, false
	}
	return o.CardAlias, true
}

// HasCardAlias returns a boolean if a field has been set.
func (o *CardEMI) HasCardAlias() bool {
	if o != nil && !IsNil(o.CardAlias) {
		return true
	}

	return false
}

// SetCardAlias gets a reference to the given string and assigns it to the CardAlias field.
func (o *CardEMI) SetCardAlias(v string) {
	o.CardAlias = &v
}

// GetCardBankName returns the CardBankName field value
func (o *CardEMI) GetCardBankName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CardBankName
}

// GetCardBankNameOk returns a tuple with the CardBankName field value
// and a boolean to check if the value has been set.
func (o *CardEMI) GetCardBankNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardBankName, true
}

// SetCardBankName sets field value
func (o *CardEMI) SetCardBankName(v string) {
	o.CardBankName = v
}

// GetEmiTenure returns the EmiTenure field value
func (o *CardEMI) GetEmiTenure() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EmiTenure
}

// GetEmiTenureOk returns a tuple with the EmiTenure field value
// and a boolean to check if the value has been set.
func (o *CardEMI) GetEmiTenureOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmiTenure, true
}

// SetEmiTenure sets field value
func (o *CardEMI) SetEmiTenure(v int32) {
	o.EmiTenure = v
}

func (o CardEMI) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CardEMI) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channel"] = o.Channel
	toSerialize["card_number"] = o.CardNumber
	if !IsNil(o.CardHolderName) {
		toSerialize["card_holder_name"] = o.CardHolderName
	}
	toSerialize["card_expiry_mm"] = o.CardExpiryMm
	toSerialize["card_expiry_yy"] = o.CardExpiryYy
	toSerialize["card_cvv"] = o.CardCvv
	if !IsNil(o.CardAlias) {
		toSerialize["card_alias"] = o.CardAlias
	}
	toSerialize["card_bank_name"] = o.CardBankName
	toSerialize["emi_tenure"] = o.EmiTenure
	return toSerialize, nil
}

type NullableCardEMI struct {
	value *CardEMI
	isSet bool
}

func (v NullableCardEMI) Get() *CardEMI {
	return v.value
}

func (v *NullableCardEMI) Set(val *CardEMI) {
	v.value = val
	v.isSet = true
}

func (v NullableCardEMI) IsSet() bool {
	return v.isSet
}

func (v *NullableCardEMI) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardEMI(val *CardEMI) *NullableCardEMI {
	return &NullableCardEMI{value: val, isSet: true}
}

func (v NullableCardEMI) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardEMI) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


