/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2026-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"fmt"
	"strings"
)

var _ = fmt.Errorf

// checks if the TerminalPagination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TerminalPagination{}

// TerminalPagination Use this object to configure pagination for terminal transaction results.
type TerminalPagination struct {
	// Page number for the requested results. Default value is 1.
	PageNumber *int32 `json:"page_number,omitempty"`
	// Number of transactions to return per page. Default value is 25.
	PageSize *int32 `json:"page_size,omitempty"`
}


func (o TerminalPagination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TerminalPagination) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PageNumber) {
		toSerialize["page_number"] = o.PageNumber
	}
	if !IsNil(o.PageSize) {
		toSerialize["page_size"] = o.PageSize
	}
	return toSerialize, nil
}


