/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2026-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"fmt"
	"strings"
)

var _ = fmt.Errorf

// checks if the OrderUpdateRefundRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderUpdateRefundRequest{}

// OrderUpdateRefundRequest update refund request object.
type OrderUpdateRefundRequest struct {
	// Allowed values: [\"CANCELLED\"].
	RefundStatus string `json:"refund_status"`
	// Add remarks for your reference.
	Remarks *string `json:"remarks,omitempty"`
}


func (o OrderUpdateRefundRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderUpdateRefundRequest) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	toSerialize["refund_status"] = o.RefundStatus
	if !IsNil(o.Remarks) {
		toSerialize["remarks"] = o.Remarks
	}
	return toSerialize, nil
}


