/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2025-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"fmt"
	"strings"
)

var _ = fmt.Errorf

// checks if the ExtendedCustomerDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExtendedCustomerDetails{}

// ExtendedCustomerDetails Recent Customer details associated with the order.
type ExtendedCustomerDetails struct {
	// A unique identifier for the customer. Use alphanumeric values only.
	CustomerId *string `json:"customer_id,omitempty"`
	// Customer email address.
	CustomerEmail *string `json:"customer_email,omitempty"`
	// Customer phone number.
	CustomerPhone *string `json:"customer_phone,omitempty"`
	// Name of the customer.
	CustomerName *string `json:"customer_name,omitempty"`
	// Customer identifier at Cashfree. You will get this when you create/get customer
	CustomerUid *string `json:"customer_uid,omitempty"`
}


func (o ExtendedCustomerDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExtendedCustomerDetails) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerId) {
		toSerialize["customer_id"] = o.CustomerId
	}
	if !IsNil(o.CustomerEmail) {
		toSerialize["customer_email"] = o.CustomerEmail
	}
	if !IsNil(o.CustomerPhone) {
		toSerialize["customer_phone"] = o.CustomerPhone
	}
	if !IsNil(o.CustomerName) {
		toSerialize["customer_name"] = o.CustomerName
	}
	if !IsNil(o.CustomerUid) {
		toSerialize["customer_uid"] = o.CustomerUid
	}
	return toSerialize, nil
}


