/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Error when resource requested is not found
 * @export
 * @interface ApiError404
 */
export interface ApiError404 {
    /**
     * 
     * @type {string}
     * @memberof ApiError404
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiError404
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiError404
     */
    'help'?: string;
    /**
     * invalid_request_error
     * @type {string}
     * @memberof ApiError404
     */
    'type'?: TYPE;
}

export const TYPE = {
    INVALID_REQUEST_ERROR: "invalid_request_error",
    UNKNOWN_DEFAULT_OPEN_API: "11184809"
} as const;

export type TYPE = typeof TYPE[keyof typeof TYPE];

