/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * App payment method
 * @export
 * @interface App
 */
export interface App {
    /**
     * Specify the channel through which the payment must be processed.
     * @type {string}
     * @memberof App
     */
    'channel': string;
    /**
     * Specify the provider through which the payment must be processed.
     * @type {string}
     * @memberof App
     */
    'provider': PROVIDER;
    /**
     * Customer phone number associated with a wallet for payment.
     * @type {string}
     * @memberof App
     */
    'phone': string;
}

export const PROVIDER = {
    GPAY: "gpay",
    PHONEPE: "phonepe",
    OLA: "ola",
    PAYTM: "paytm",
    AMAZON: "amazon",
    AIRTEL: "airtel",
    FREECHARGE: "freecharge",
    MOBIKWIK: "mobikwik",
    JIO: "jio",
    UNKNOWN_DEFAULT_OPEN_API: "11184809"
} as const;

export type PROVIDER = typeof PROVIDER[keyof typeof PROVIDER];

