/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Offer validation object
 * @export
 * @interface OfferValidations
 */
export interface OfferValidations {
    /**
     * Minimum Amount for Offer to be Applicable
     * @type {float32}
     * @memberof OfferValidations
     */
    'min_amount'?: float32;
    /**
     * Maximum Amount for Offer to be Applicable
     * @type {float32}
     * @memberof OfferValidations
     */
    'max_allowed': float32;
    /**
     * 
     * @type {OfferValidationsResponsePaymentMethod}
     * @memberof OfferValidations
     */
    'payment_method': OfferValidationsResponsePaymentMethod;
}
