/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Order Pay response once you create a transaction for that order
 * @export
 * @interface PayOrderEntity
 */
export interface PayOrderEntity {
    /**
     * total amount payable
     * @type {float32}
     * @memberof PayOrderEntity
     */
    'payment_amount'?: float32;
    /**
     * Payment identifier created by Cashfree
     * @type {string}
     * @memberof PayOrderEntity
     */
    'cf_payment_id'?: string;
    /**
     * One of [\"upi\", \"netbanking\", \"card\", \"app\", \"cardless_emi\", \"paylater\", \"banktransfer\"] 
     * @type {string}
     * @memberof PayOrderEntity
     */
    'payment_method'?: PAYMENT_METHOD;
    /**
     * One of [\"link\", \"collect\", \"qrcode\"]. In an older version we used to support different channels like 'gpay', 'phonepe' etc. However, we now support only the following channels - link, collect and qrcode. To process payments using gpay, you will have to provide channel as 'link' and provider as 'gpay'
     * @type {string}
     * @memberof PayOrderEntity
     */
    'channel'?: CHANNEL;
    /**
     * One of [\"link\", \"custom\", \"form\"]
     * @type {string}
     * @memberof PayOrderEntity
     */
    'action'?: ACTION;
    /**
     * 
     * @type {OrderPayData}
     * @memberof PayOrderEntity
     */
    'data'?: OrderPayData;
}

export const PAYMENT_METHOD = {
    NETBANKING: "netbanking",
    CARD: "card",
    UPI: "upi",
    APP: "app",
    CARDLESS_EMI: "cardless_emi",
    PAYLATER: "paylater",
    BANKTRANSFER: "banktransfer",
    UNKNOWN_DEFAULT_OPEN_API: "11184809"
} as const;

export type PAYMENT_METHOD = typeof PAYMENT_METHOD[keyof typeof PAYMENT_METHOD];
export const CHANNEL = {
    LINK: "link",
    COLLECT: "collect",
    QRCODE: "qrcode",
    POST: "post",
    UNKNOWN_DEFAULT_OPEN_API: "11184809"
} as const;

export type CHANNEL = typeof CHANNEL[keyof typeof CHANNEL];
export const ACTION = {
    LINK: "link",
    CUSTOM: "custom",
    FORM: "form",
    POST: "post",
    UNKNOWN_DEFAULT_OPEN_API: "11184809"
} as const;

export type ACTION = typeof ACTION[keyof typeof ACTION];

