/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2022-09-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"strings"
)

// checks if the OfferEntity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OfferEntity{}

// OfferEntity Offer entity object
type OfferEntity struct {
	OfferId *string `json:"offer_id,omitempty"`
	OfferStatus *string `json:"offer_status,omitempty"`
	OfferMeta *OfferMeta `json:"offer_meta,omitempty"`
	OfferTnc *OfferTnc `json:"offer_tnc,omitempty"`
	OfferDetails *OfferDetails `json:"offer_details,omitempty"`
	OfferValidations *OfferValidations `json:"offer_validations,omitempty"`
}


func (o OfferEntity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OfferEntity) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OfferId) {
		toSerialize["offer_id"] = o.OfferId
	}
	if !IsNil(o.OfferStatus) {
		toSerialize["offer_status"] = o.OfferStatus
	}
	if !IsNil(o.OfferMeta) {
		toSerialize["offer_meta"] = o.OfferMeta
	}
	if !IsNil(o.OfferTnc) {
		toSerialize["offer_tnc"] = o.OfferTnc
	}
	if !IsNil(o.OfferDetails) {
		toSerialize["offer_details"] = o.OfferDetails
	}
	if !IsNil(o.OfferValidations) {
		toSerialize["offer_validations"] = o.OfferValidations
	}
	return toSerialize, nil
}



