/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Use to split order when cashfree's Easy Split is enabled for your account.
 * @export
 * @interface VendorSplit
 */
export interface VendorSplit {
    /**
     * Vendor id created in Cashfree system
     * @type {string}
     * @memberof VendorSplit
     */
    'vendor_id': string;
    /**
     * Amount which will be associated with this vendor
     * @type {float32}
     * @memberof VendorSplit
     */
    'amount'?: float32;
    /**
     * Percentage of order amount which shall get added to vendor account
     * @type {float32}
     * @memberof VendorSplit
     */
    'percentage'?: float32;
    /**
     * Custom Tags in thr form of {\"key\":\"value\"} which can be passed for an order. A maximum of 10 tags can be added
     * @type {map[string]map[string]interface{}}
     * @memberof VendorSplit
     */
    'tags'?: map[string]map[string]interface{};
}
