/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2023-08-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"strings"
)

// checks if the SplitAfterPaymentRequestSplitInnerTagsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SplitAfterPaymentRequestSplitInnerTagsInner{}

// SplitAfterPaymentRequestSplitInnerTagsInner struct for SplitAfterPaymentRequestSplitInnerTagsInner
type SplitAfterPaymentRequestSplitInnerTagsInner struct {
	KeyValue1 *string `json:"Key Value 1,omitempty"`
	KeyValue2 *string `json:"Key Value 2,omitempty"`
}


func (o SplitAfterPaymentRequestSplitInnerTagsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SplitAfterPaymentRequestSplitInnerTagsInner) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.KeyValue1) {
		toSerialize["Key Value 1"] = o.KeyValue1
	}
	if !IsNil(o.KeyValue2) {
		toSerialize["Key Value 2"] = o.KeyValue2
	}
	return toSerialize, nil
}



