/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2023-08-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"strings"
)

// checks if the VendorDocumentDownloadResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VendorDocumentDownloadResponse{}

// VendorDocumentDownloadResponse Download Vendor Document
type VendorDocumentDownloadResponse struct {
	DownloadUrl *string `json:"download_url,omitempty"`
}


func (o VendorDocumentDownloadResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VendorDocumentDownloadResponse) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DownloadUrl) {
		toSerialize["download_url"] = o.DownloadUrl
	}
	return toSerialize, nil
}



