/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2022-09-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
)

// checks if the WHdata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WHdata{}

// WHdata webhook object
type WHdata struct {
	Order *WHorder `json:"order,omitempty"`
	Payment *PaymentEntity `json:"payment,omitempty"`
	CustomerDetails *WHcustomerDetails `json:"customer_details,omitempty"`
}

// NewWHdata instantiates a new WHdata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWHdata() *WHdata {
	this := WHdata{}
	return &this
}

// NewWHdataWithDefaults instantiates a new WHdata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWHdataWithDefaults() *WHdata {
	this := WHdata{}
	return &this
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *WHdata) GetOrder() WHorder {
	if o == nil || IsNil(o.Order) {
		var ret WHorder
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WHdata) GetOrderOk() (*WHorder, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *WHdata) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given WHorder and assigns it to the Order field.
func (o *WHdata) SetOrder(v WHorder) {
	o.Order = &v
}

// GetPayment returns the Payment field value if set, zero value otherwise.
func (o *WHdata) GetPayment() PaymentEntity {
	if o == nil || IsNil(o.Payment) {
		var ret PaymentEntity
		return ret
	}
	return *o.Payment
}

// GetPaymentOk returns a tuple with the Payment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WHdata) GetPaymentOk() (*PaymentEntity, bool) {
	if o == nil || IsNil(o.Payment) {
		return nil, false
	}
	return o.Payment, true
}

// HasPayment returns a boolean if a field has been set.
func (o *WHdata) HasPayment() bool {
	if o != nil && !IsNil(o.Payment) {
		return true
	}

	return false
}

// SetPayment gets a reference to the given PaymentEntity and assigns it to the Payment field.
func (o *WHdata) SetPayment(v PaymentEntity) {
	o.Payment = &v
}

// GetCustomerDetails returns the CustomerDetails field value if set, zero value otherwise.
func (o *WHdata) GetCustomerDetails() WHcustomerDetails {
	if o == nil || IsNil(o.CustomerDetails) {
		var ret WHcustomerDetails
		return ret
	}
	return *o.CustomerDetails
}

// GetCustomerDetailsOk returns a tuple with the CustomerDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WHdata) GetCustomerDetailsOk() (*WHcustomerDetails, bool) {
	if o == nil || IsNil(o.CustomerDetails) {
		return nil, false
	}
	return o.CustomerDetails, true
}

// HasCustomerDetails returns a boolean if a field has been set.
func (o *WHdata) HasCustomerDetails() bool {
	if o != nil && !IsNil(o.CustomerDetails) {
		return true
	}

	return false
}

// SetCustomerDetails gets a reference to the given WHcustomerDetails and assigns it to the CustomerDetails field.
func (o *WHdata) SetCustomerDetails(v WHcustomerDetails) {
	o.CustomerDetails = &v
}

func (o WHdata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WHdata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.Payment) {
		toSerialize["payment"] = o.Payment
	}
	if !IsNil(o.CustomerDetails) {
		toSerialize["customer_details"] = o.CustomerDetails
	}
	return toSerialize, nil
}

type NullableWHdata struct {
	value *WHdata
	isSet bool
}

func (v NullableWHdata) Get() *WHdata {
	return v.value
}

func (v *NullableWHdata) Set(val *WHdata) {
	v.value = val
	v.isSet = true
}

func (v NullableWHdata) IsSet() bool {
	return v.isSet
}

func (v *NullableWHdata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWHdata(val *WHdata) *NullableWHdata {
	return &NullableWHdata{value: val, isSet: true}
}

func (v NullableWHdata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWHdata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


