/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2026-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"fmt"
	"strings"
)

var _ = fmt.Errorf

// checks if the OfferExtendedDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OfferExtendedDetails{}

// OfferExtendedDetails Details of the offer which got applied to the paid order.
type OfferExtendedDetails struct {
	[]string
}


func (o OfferExtendedDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OfferExtendedDetails) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	serialized[]string, err[]string := json.Marshal(o.[]string)
	if err[]string != nil {
		return map[string]interface{}{}, err[]string
	}
	err[]string = json.Unmarshal([]byte(serialized[]string), &toSerialize)
	if err[]string != nil {
		return map[string]interface{}{}, err[]string
	}
	return toSerialize, nil
}


