/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2025-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"fmt"
	"strings"
)

var _ = fmt.Errorf

// checks if the SplitOrderReconSuccessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SplitOrderReconSuccessResponse{}

// SplitOrderReconSuccessResponse Split Order Reconciliation Request Body
type SplitOrderReconSuccessResponse struct {
	Settlement *SplitOrderReconSuccessResponseSettlement `json:"settlement,omitempty"`
	// List of refunds associated with the order, if any.
	Refunds []map[string]interface{} `json:"refunds,omitempty"`
	// List of vendor settlements associated with the split settlement.
	Vendors []SplitOrderReconSuccessResponseVendorsInner `json:"vendors,omitempty"`
}


func (o SplitOrderReconSuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SplitOrderReconSuccessResponse) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Settlement) {
		toSerialize["settlement"] = o.Settlement
	}
	if !IsNil(o.Refunds) {
		toSerialize["refunds"] = o.Refunds
	}
	if !IsNil(o.Vendors) {
		toSerialize["vendors"] = o.Vendors
	}
	return toSerialize, nil
}


