/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The complete order entity
 * @export
 * @interface OrderEntity
 */
export interface OrderEntity {
    /**
     * unique id generated by cashfree for your order
     * @type {string}
     * @memberof OrderEntity
     */
    'cf_order_id'?: string;
    /**
     * order_id sent during the api request
     * @type {string}
     * @memberof OrderEntity
     */
    'order_id'?: string;
    /**
     * Type of the entity.
     * @type {string}
     * @memberof OrderEntity
     */
    'entity'?: string;
    /**
     * Currency of the order. Example INR
     * @type {string}
     * @memberof OrderEntity
     */
    'order_currency'?: string;
    /**
     * 
     * @type {float32}
     * @memberof OrderEntity
     */
    'order_amount'?: float32;
    /**
     * Possible values are  - `ACTIVE`: Order does not have a sucessful transaction yet - `PAID`: Order is PAID with one successful transaction - `EXPIRED`: Order was not PAID and not it has expired. No transaction can be initiated for an EXPIRED order. `TERMINATED`: Order terminated `TERMINATION_REQUESTED`: Order termination requested
     * @type {string}
     * @memberof OrderEntity
     */
    'order_status'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderEntity
     */
    'payment_session_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderEntity
     */
    'order_expiry_time'?: string;
    /**
     * Additional note for order
     * @type {string}
     * @memberof OrderEntity
     */
    'order_note'?: string;
    /**
     * When the order was created at cashfree's server
     * @type {string}
     * @memberof OrderEntity
     */
    'created_at'?: string;
    /**
     * 
     * @type {[]VendorSplit}
     * @memberof OrderEntity
     */
    'order_splits'?: []VendorSplit;
    /**
     * 
     * @type {CustomerDetailsResponse}
     * @memberof OrderEntity
     */
    'customer_details'?: CustomerDetailsResponse;
    /**
     * 
     * @type {OrderMeta}
     * @memberof OrderEntity
     */
    'order_meta'?: OrderMeta;
    /**
     * Custom Tags in thr form of {\"key\":\"value\"} which can be passed for an order. A maximum of 10 tags can be added
     * @type {map[string]string}
     * @memberof OrderEntity
     */
    'order_tags'?: map[string]string;
    /**
     * 
     * @type {CartDetailsEntity}
     * @memberof OrderEntity
     */
    'cart_details'?: CartDetailsEntity;
    /**
     * 
     * @type {TerminalData}
     * @memberof OrderEntity
     */
    'terminal_data'?: TerminalData;
    /**
     * 
     * @type {OrderEntityProducts}
     * @memberof OrderEntity
     */
    'products'?: OrderEntityProducts;
}
