/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2025-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"fmt"
	"strings"
)

var _ = fmt.Errorf

// checks if the EligibilityMethodItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EligibilityMethodItem{}

// EligibilityMethodItem Eligibile payment method object
type EligibilityMethodItem struct {
	// Indicates whether the payment method is eligible.
	Eligibility *bool `json:"eligibility,omitempty"`
	// Type of entity (e.g., \"payment_methods\").
	EntityType *string `json:"entity_type,omitempty"`
	// Payment method (e.g., enach, pnach, upi, card).
	EntityValue *string `json:"entity_value,omitempty"`
	EntityDetails *EligibilityMethodItemEntityDetails `json:"entity_details,omitempty"`
}


func (o EligibilityMethodItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EligibilityMethodItem) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Eligibility) {
		toSerialize["eligibility"] = o.Eligibility
	}
	if !IsNil(o.EntityType) {
		toSerialize["entity_type"] = o.EntityType
	}
	if !IsNil(o.EntityValue) {
		toSerialize["entity_value"] = o.EntityValue
	}
	if !IsNil(o.EntityDetails) {
		toSerialize["entity_details"] = o.EntityDetails
	}
	return toSerialize, nil
}


