/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2026-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"fmt"
	"strings"
)

var _ = fmt.Errorf

// IncidentObjectPaymentMethod - struct for IncidentObjectPaymentMethod
type IncidentObjectPaymentMethod struct {
	CardDowntime *CardDowntime
	NetBankingDowntime *NetBankingDowntime
	UPIDowntime *UPIDowntime
	WalletDowntime *WalletDowntime
}

// CardDowntimeAsIncidentObjectPaymentMethod is a convenience function that returns CardDowntime wrapped in IncidentObjectPaymentMethod
func CardDowntimeAsIncidentObjectPaymentMethod(v *CardDowntime) IncidentObjectPaymentMethod {
	return IncidentObjectPaymentMethod{
		CardDowntime: v,
	}
}

// NetBankingDowntimeAsIncidentObjectPaymentMethod is a convenience function that returns NetBankingDowntime wrapped in IncidentObjectPaymentMethod
func NetBankingDowntimeAsIncidentObjectPaymentMethod(v *NetBankingDowntime) IncidentObjectPaymentMethod {
	return IncidentObjectPaymentMethod{
		NetBankingDowntime: v,
	}
}

// UPIDowntimeAsIncidentObjectPaymentMethod is a convenience function that returns UPIDowntime wrapped in IncidentObjectPaymentMethod
func UPIDowntimeAsIncidentObjectPaymentMethod(v *UPIDowntime) IncidentObjectPaymentMethod {
	return IncidentObjectPaymentMethod{
		UPIDowntime: v,
	}
}

// WalletDowntimeAsIncidentObjectPaymentMethod is a convenience function that returns WalletDowntime wrapped in IncidentObjectPaymentMethod
func WalletDowntimeAsIncidentObjectPaymentMethod(v *WalletDowntime) IncidentObjectPaymentMethod {
	return IncidentObjectPaymentMethod{
		WalletDowntime: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *IncidentObjectPaymentMethod) UnmarshalJSON(data []byte) error {
		var err error





	match := 0


	// try to unmarshal data into CardDowntime

	err = json.Unmarshal(data, &dst.CardDowntime)

	if err == nil {

		jsonCardDowntime, _ := json.Marshal(dst.CardDowntime)

		if strings.Contains(string(jsonCardDowntime), "{}") || strings.Contains(string(jsonCardDowntime), "null") { // empty struct

			dst.CardDowntime = nil

		} else {

			match++

		}

	} else {

		dst.CardDowntime = nil

	}


	// try to unmarshal data into NetBankingDowntime

	err = json.Unmarshal(data, &dst.NetBankingDowntime)

	if err == nil {

		jsonNetBankingDowntime, _ := json.Marshal(dst.NetBankingDowntime)

		if strings.Contains(string(jsonNetBankingDowntime), "{}") || strings.Contains(string(jsonNetBankingDowntime), "null") { // empty struct

			dst.NetBankingDowntime = nil

		} else {

			match++

		}

	} else {

		dst.NetBankingDowntime = nil

	}


	// try to unmarshal data into UPIDowntime

	err = json.Unmarshal(data, &dst.UPIDowntime)

	if err == nil {

		jsonUPIDowntime, _ := json.Marshal(dst.UPIDowntime)

		if strings.Contains(string(jsonUPIDowntime), "{}") || strings.Contains(string(jsonUPIDowntime), "null") { // empty struct

			dst.UPIDowntime = nil

		} else {

			match++

		}

	} else {

		dst.UPIDowntime = nil

	}


	// try to unmarshal data into WalletDowntime

	err = json.Unmarshal(data, &dst.WalletDowntime)

	if err == nil {

		jsonWalletDowntime, _ := json.Marshal(dst.WalletDowntime)

		if strings.Contains(string(jsonWalletDowntime), "{}") || strings.Contains(string(jsonWalletDowntime), "null") { // empty struct

			dst.WalletDowntime = nil

		} else {

			match++

		}

	} else {

		dst.WalletDowntime = nil

	}


	if match > 1 { // more than 1 match

		// reset to nil


		dst.CardDowntime = nil


		dst.NetBankingDowntime = nil


		dst.UPIDowntime = nil


		dst.WalletDowntime = nil


		return fmt.Errorf("data matches more than one schema in oneOf(IncidentObjectPaymentMethod)")

	} else if match == 1 {

		return nil // exactly one match

	} else { // no match

		return fmt.Errorf("data failed to match schemas in oneOf(IncidentObjectPaymentMethod)")

	}



}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src IncidentObjectPaymentMethod) MarshalJSON() ([]byte, error) {
	if src.CardDowntime != nil {
		return json.Marshal(&src.CardDowntime)
	}

	if src.NetBankingDowntime != nil {
		return json.Marshal(&src.NetBankingDowntime)
	}

	if src.UPIDowntime != nil {
		return json.Marshal(&src.UPIDowntime)
	}

	if src.WalletDowntime != nil {
		return json.Marshal(&src.WalletDowntime)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *IncidentObjectPaymentMethod) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CardDowntime != nil {
		return obj.CardDowntime
	}

	if obj.NetBankingDowntime != nil {
		return obj.NetBankingDowntime
	}

	if obj.UPIDowntime != nil {
		return obj.UPIDowntime
	}

	if obj.WalletDowntime != nil {
		return obj.WalletDowntime
	}

	// all schemas are nil
	return nil
}


