/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2025-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"fmt"
	"strings"
)

var _ = fmt.Errorf

// checks if the SplitAfterPaymentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SplitAfterPaymentRequest{}

// SplitAfterPaymentRequest Split After Payment Request
type SplitAfterPaymentRequest struct {
	// Specify the vendors order split details.
	Split []SplitAfterPaymentRequestSplitInner `json:"split"`
	// Specify if you want to end the split or continue creating further splits in future.
	DisableSplit *bool `json:"disable_split,omitempty"`
}


func (o SplitAfterPaymentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SplitAfterPaymentRequest) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	toSerialize["split"] = o.Split
	if !IsNil(o.DisableSplit) {
		toSerialize["disable_split"] = o.DisableSplit
	}
	return toSerialize, nil
}


