/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2022-09-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
)

// checks if the EligibilityOfferEntity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EligibilityOfferEntity{}

// EligibilityOfferEntity Eligible offer object
type EligibilityOfferEntity struct {
	Eligibility *bool `json:"eligibility,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	EntityValue *string `json:"entity_value,omitempty"`
	EntityDetails *OfferEntity `json:"entity_details,omitempty"`
}

// NewEligibilityOfferEntity instantiates a new EligibilityOfferEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEligibilityOfferEntity() *EligibilityOfferEntity {
	this := EligibilityOfferEntity{}
	return &this
}

// NewEligibilityOfferEntityWithDefaults instantiates a new EligibilityOfferEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEligibilityOfferEntityWithDefaults() *EligibilityOfferEntity {
	this := EligibilityOfferEntity{}
	return &this
}

// GetEligibility returns the Eligibility field value if set, zero value otherwise.
func (o *EligibilityOfferEntity) GetEligibility() bool {
	if o == nil || IsNil(o.Eligibility) {
		var ret bool
		return ret
	}
	return *o.Eligibility
}

// GetEligibilityOk returns a tuple with the Eligibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EligibilityOfferEntity) GetEligibilityOk() (*bool, bool) {
	if o == nil || IsNil(o.Eligibility) {
		return nil, false
	}
	return o.Eligibility, true
}

// HasEligibility returns a boolean if a field has been set.
func (o *EligibilityOfferEntity) HasEligibility() bool {
	if o != nil && !IsNil(o.Eligibility) {
		return true
	}

	return false
}

// SetEligibility gets a reference to the given bool and assigns it to the Eligibility field.
func (o *EligibilityOfferEntity) SetEligibility(v bool) {
	o.Eligibility = &v
}

// GetEntityType returns the EntityType field value if set, zero value otherwise.
func (o *EligibilityOfferEntity) GetEntityType() string {
	if o == nil || IsNil(o.EntityType) {
		var ret string
		return ret
	}
	return *o.EntityType
}

// GetEntityTypeOk returns a tuple with the EntityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EligibilityOfferEntity) GetEntityTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EntityType) {
		return nil, false
	}
	return o.EntityType, true
}

// HasEntityType returns a boolean if a field has been set.
func (o *EligibilityOfferEntity) HasEntityType() bool {
	if o != nil && !IsNil(o.EntityType) {
		return true
	}

	return false
}

// SetEntityType gets a reference to the given string and assigns it to the EntityType field.
func (o *EligibilityOfferEntity) SetEntityType(v string) {
	o.EntityType = &v
}

// GetEntityValue returns the EntityValue field value if set, zero value otherwise.
func (o *EligibilityOfferEntity) GetEntityValue() string {
	if o == nil || IsNil(o.EntityValue) {
		var ret string
		return ret
	}
	return *o.EntityValue
}

// GetEntityValueOk returns a tuple with the EntityValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EligibilityOfferEntity) GetEntityValueOk() (*string, bool) {
	if o == nil || IsNil(o.EntityValue) {
		return nil, false
	}
	return o.EntityValue, true
}

// HasEntityValue returns a boolean if a field has been set.
func (o *EligibilityOfferEntity) HasEntityValue() bool {
	if o != nil && !IsNil(o.EntityValue) {
		return true
	}

	return false
}

// SetEntityValue gets a reference to the given string and assigns it to the EntityValue field.
func (o *EligibilityOfferEntity) SetEntityValue(v string) {
	o.EntityValue = &v
}

// GetEntityDetails returns the EntityDetails field value if set, zero value otherwise.
func (o *EligibilityOfferEntity) GetEntityDetails() OfferEntity {
	if o == nil || IsNil(o.EntityDetails) {
		var ret OfferEntity
		return ret
	}
	return *o.EntityDetails
}

// GetEntityDetailsOk returns a tuple with the EntityDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EligibilityOfferEntity) GetEntityDetailsOk() (*OfferEntity, bool) {
	if o == nil || IsNil(o.EntityDetails) {
		return nil, false
	}
	return o.EntityDetails, true
}

// HasEntityDetails returns a boolean if a field has been set.
func (o *EligibilityOfferEntity) HasEntityDetails() bool {
	if o != nil && !IsNil(o.EntityDetails) {
		return true
	}

	return false
}

// SetEntityDetails gets a reference to the given OfferEntity and assigns it to the EntityDetails field.
func (o *EligibilityOfferEntity) SetEntityDetails(v OfferEntity) {
	o.EntityDetails = &v
}

func (o EligibilityOfferEntity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EligibilityOfferEntity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Eligibility) {
		toSerialize["eligibility"] = o.Eligibility
	}
	if !IsNil(o.EntityType) {
		toSerialize["entity_type"] = o.EntityType
	}
	if !IsNil(o.EntityValue) {
		toSerialize["entity_value"] = o.EntityValue
	}
	if !IsNil(o.EntityDetails) {
		toSerialize["entity_details"] = o.EntityDetails
	}
	return toSerialize, nil
}

type NullableEligibilityOfferEntity struct {
	value *EligibilityOfferEntity
	isSet bool
}

func (v NullableEligibilityOfferEntity) Get() *EligibilityOfferEntity {
	return v.value
}

func (v *NullableEligibilityOfferEntity) Set(val *EligibilityOfferEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableEligibilityOfferEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableEligibilityOfferEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEligibilityOfferEntity(val *EligibilityOfferEntity) *NullableEligibilityOfferEntity {
	return &NullableEligibilityOfferEntity{value: val, isSet: true}
}

func (v NullableEligibilityOfferEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEligibilityOfferEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


