/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2025-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"strings"
)

// checks if the KycDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KycDetails{}

// KycDetails struct for KycDetails
type KycDetails struct {
	AccountType *string `json:"account_type,omitempty"`
	BusinessType *string `json:"business_type,omitempty"`
	Uidai *float32 `json:"uidai,omitempty"`
	Gst *string `json:"gst,omitempty"`
	Cin *string `json:"cin,omitempty"`
	Pan *string `json:"pan,omitempty"`
	PassportNumber *string `json:"passport_number,omitempty"`
	DrivingLicense *string `json:"driving_license,omitempty"`
	VoterId *string `json:"voter_id,omitempty"`
}


func (o KycDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KycDetails) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountType) {
		toSerialize["account_type"] = o.AccountType
	}
	if !IsNil(o.BusinessType) {
		toSerialize["business_type"] = o.BusinessType
	}
	if !IsNil(o.Uidai) {
		toSerialize["uidai"] = o.Uidai
	}
	if !IsNil(o.Gst) {
		toSerialize["gst"] = o.Gst
	}
	if !IsNil(o.Cin) {
		toSerialize["cin"] = o.Cin
	}
	if !IsNil(o.Pan) {
		toSerialize["pan"] = o.Pan
	}
	if !IsNil(o.PassportNumber) {
		toSerialize["passport_number"] = o.PassportNumber
	}
	if !IsNil(o.DrivingLicense) {
		toSerialize["driving_license"] = o.DrivingLicense
	}
	if !IsNil(o.VoterId) {
		toSerialize["voter_id"] = o.VoterId
	}
	return toSerialize, nil
}



