/*
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

API version: 2023-08-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg

import (
	"encoding/json"
	"strings"
)

// checks if the SplitAfterPaymentRequestSplitInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SplitAfterPaymentRequestSplitInner{}

// SplitAfterPaymentRequestSplitInner struct for SplitAfterPaymentRequestSplitInner
type SplitAfterPaymentRequestSplitInner struct {
	// Specify the merchant vendor ID to split the payment.
	VendorId *string `json:"vendor_id,omitempty"`
	// Specify the amount to be split to the vendor.
	Amount *float32 `json:"amount,omitempty"`
	// Specify the percentage of amount to be split.
	Percentage *float32 `json:"percentage,omitempty"`
	// Custom Tags in thr form of {\"key\":\"value\"} which can be passed for an order. A maximum of 10 tags can be added
	Tags *map[string]string `json:"tags,omitempty"`
}


func (o SplitAfterPaymentRequestSplitInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SplitAfterPaymentRequestSplitInner) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VendorId) {
		toSerialize["vendor_id"] = o.VendorId
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Percentage) {
		toSerialize["percentage"] = o.Percentage
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}



