/*
New Payment Gateway APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2022-01-01
Contact: nextgenapi@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg_sdk_go

import (
	"encoding/json"
)

// CFUPIPayment struct for CFUPIPayment
type CFUPIPayment struct {
	Upi CFUPI `json:"upi"`
}

// NewCFUPIPayment instantiates a new CFUPIPayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCFUPIPayment(upi CFUPI) *CFUPIPayment {
	this := CFUPIPayment{}
	this.Upi = upi
	return &this
}

// NewCFUPIPaymentWithDefaults instantiates a new CFUPIPayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCFUPIPaymentWithDefaults() *CFUPIPayment {
	this := CFUPIPayment{}
	return &this
}

// GetUpi returns the Upi field value
func (o *CFUPIPayment) GetUpi() CFUPI {
	if o == nil {
		var ret CFUPI
		return ret
	}

	return o.Upi
}

// GetUpiOk returns a tuple with the Upi field value
// and a boolean to check if the value has been set.
func (o *CFUPIPayment) GetUpiOk() (*CFUPI, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Upi, true
}

// SetUpi sets field value
func (o *CFUPIPayment) SetUpi(v CFUPI) {
	o.Upi = v
}

func (o CFUPIPayment) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["upi"] = o.Upi
	}
	return json.Marshal(toSerialize)
}

type NullableCFUPIPayment struct {
	value *CFUPIPayment
	isSet bool
}

func (v NullableCFUPIPayment) Get() *CFUPIPayment {
	return v.value
}

func (v *NullableCFUPIPayment) Set(val *CFUPIPayment) {
	v.value = val
	v.isSet = true
}

func (v NullableCFUPIPayment) IsSet() bool {
	return v.isSet
}

func (v *NullableCFUPIPayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCFUPIPayment(val *CFUPIPayment) *NullableCFUPIPayment {
	return &NullableCFUPIPayment{value: val, isSet: true}
}

func (v NullableCFUPIPayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCFUPIPayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


