/*
New Payment Gateway APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2022-01-01
Contact: nextgenapi@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg_sdk_go

import (
	"encoding/json"
)

// CFPaymentsEntityNetbankingPayment struct for CFPaymentsEntityNetbankingPayment
type CFPaymentsEntityNetbankingPayment struct {
	Channel string `json:"channel"`
	NetbankingBankCode string `json:"netbanking_bank_code"`
	NetbankingBankName string `json:"netbanking_bank_name"`
}

// NewCFPaymentsEntityNetbankingPayment instantiates a new CFPaymentsEntityNetbankingPayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCFPaymentsEntityNetbankingPayment(channel string, netbankingBankCode string, netbankingBankName string) *CFPaymentsEntityNetbankingPayment {
	this := CFPaymentsEntityNetbankingPayment{}
	this.Channel = channel
	this.NetbankingBankCode = netbankingBankCode
	this.NetbankingBankName = netbankingBankName
	return &this
}

// NewCFPaymentsEntityNetbankingPaymentWithDefaults instantiates a new CFPaymentsEntityNetbankingPayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCFPaymentsEntityNetbankingPaymentWithDefaults() *CFPaymentsEntityNetbankingPayment {
	this := CFPaymentsEntityNetbankingPayment{}
	return &this
}

// GetChannel returns the Channel field value
func (o *CFPaymentsEntityNetbankingPayment) GetChannel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *CFPaymentsEntityNetbankingPayment) GetChannelOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *CFPaymentsEntityNetbankingPayment) SetChannel(v string) {
	o.Channel = v
}

// GetNetbankingBankCode returns the NetbankingBankCode field value
func (o *CFPaymentsEntityNetbankingPayment) GetNetbankingBankCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetbankingBankCode
}

// GetNetbankingBankCodeOk returns a tuple with the NetbankingBankCode field value
// and a boolean to check if the value has been set.
func (o *CFPaymentsEntityNetbankingPayment) GetNetbankingBankCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NetbankingBankCode, true
}

// SetNetbankingBankCode sets field value
func (o *CFPaymentsEntityNetbankingPayment) SetNetbankingBankCode(v string) {
	o.NetbankingBankCode = v
}

// GetNetbankingBankName returns the NetbankingBankName field value
func (o *CFPaymentsEntityNetbankingPayment) GetNetbankingBankName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetbankingBankName
}

// GetNetbankingBankNameOk returns a tuple with the NetbankingBankName field value
// and a boolean to check if the value has been set.
func (o *CFPaymentsEntityNetbankingPayment) GetNetbankingBankNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NetbankingBankName, true
}

// SetNetbankingBankName sets field value
func (o *CFPaymentsEntityNetbankingPayment) SetNetbankingBankName(v string) {
	o.NetbankingBankName = v
}

func (o CFPaymentsEntityNetbankingPayment) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["channel"] = o.Channel
	}
	if true {
		toSerialize["netbanking_bank_code"] = o.NetbankingBankCode
	}
	if true {
		toSerialize["netbanking_bank_name"] = o.NetbankingBankName
	}
	return json.Marshal(toSerialize)
}

type NullableCFPaymentsEntityNetbankingPayment struct {
	value *CFPaymentsEntityNetbankingPayment
	isSet bool
}

func (v NullableCFPaymentsEntityNetbankingPayment) Get() *CFPaymentsEntityNetbankingPayment {
	return v.value
}

func (v *NullableCFPaymentsEntityNetbankingPayment) Set(val *CFPaymentsEntityNetbankingPayment) {
	v.value = val
	v.isSet = true
}

func (v NullableCFPaymentsEntityNetbankingPayment) IsSet() bool {
	return v.isSet
}

func (v *NullableCFPaymentsEntityNetbankingPayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCFPaymentsEntityNetbankingPayment(val *CFPaymentsEntityNetbankingPayment) *NullableCFPaymentsEntityNetbankingPayment {
	return &NullableCFPaymentsEntityNetbankingPayment{value: val, isSet: true}
}

func (v NullableCFPaymentsEntityNetbankingPayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCFPaymentsEntityNetbankingPayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


