/*
New Payment Gateway APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2022-01-01
Contact: nextgenapi@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg_sdk_go

import (
	"encoding/json"
)

// CFNetbankingPayment struct for CFNetbankingPayment
type CFNetbankingPayment struct {
	Netbanking CFNetbanking `json:"netbanking"`
}

// NewCFNetbankingPayment instantiates a new CFNetbankingPayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCFNetbankingPayment(netbanking CFNetbanking) *CFNetbankingPayment {
	this := CFNetbankingPayment{}
	this.Netbanking = netbanking
	return &this
}

// NewCFNetbankingPaymentWithDefaults instantiates a new CFNetbankingPayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCFNetbankingPaymentWithDefaults() *CFNetbankingPayment {
	this := CFNetbankingPayment{}
	return &this
}

// GetNetbanking returns the Netbanking field value
func (o *CFNetbankingPayment) GetNetbanking() CFNetbanking {
	if o == nil {
		var ret CFNetbanking
		return ret
	}

	return o.Netbanking
}

// GetNetbankingOk returns a tuple with the Netbanking field value
// and a boolean to check if the value has been set.
func (o *CFNetbankingPayment) GetNetbankingOk() (*CFNetbanking, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Netbanking, true
}

// SetNetbanking sets field value
func (o *CFNetbankingPayment) SetNetbanking(v CFNetbanking) {
	o.Netbanking = v
}

func (o CFNetbankingPayment) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["netbanking"] = o.Netbanking
	}
	return json.Marshal(toSerialize)
}

type NullableCFNetbankingPayment struct {
	value *CFNetbankingPayment
	isSet bool
}

func (v NullableCFNetbankingPayment) Get() *CFNetbankingPayment {
	return v.value
}

func (v *NullableCFNetbankingPayment) Set(val *CFNetbankingPayment) {
	v.value = val
	v.isSet = true
}

func (v NullableCFNetbankingPayment) IsSet() bool {
	return v.isSet
}

func (v *NullableCFNetbankingPayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCFNetbankingPayment(val *CFNetbankingPayment) *NullableCFNetbankingPayment {
	return &NullableCFNetbankingPayment{value: val, isSet: true}
}

func (v NullableCFNetbankingPayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCFNetbankingPayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


