/*
New Payment Gateway APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2022-01-01
Contact: nextgenapi@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg_sdk_go

import (
	"encoding/json"
)

// CFPaymentsEntityCardPayment struct for CFPaymentsEntityCardPayment
type CFPaymentsEntityCardPayment struct {
	Channel *string `json:"channel,omitempty"`
	CardNumber *string `json:"card_number,omitempty"`
	CardNetwork *string `json:"card_network,omitempty"`
	CardType *string `json:"card_type,omitempty"`
	CardCountry *string `json:"card_country,omitempty"`
	CardBankName *string `json:"card_bank_name,omitempty"`
}

// NewCFPaymentsEntityCardPayment instantiates a new CFPaymentsEntityCardPayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCFPaymentsEntityCardPayment() *CFPaymentsEntityCardPayment {
	this := CFPaymentsEntityCardPayment{}
	return &this
}

// NewCFPaymentsEntityCardPaymentWithDefaults instantiates a new CFPaymentsEntityCardPayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCFPaymentsEntityCardPaymentWithDefaults() *CFPaymentsEntityCardPayment {
	this := CFPaymentsEntityCardPayment{}
	return &this
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *CFPaymentsEntityCardPayment) GetChannel() string {
	if o == nil || o.Channel == nil {
		var ret string
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CFPaymentsEntityCardPayment) GetChannelOk() (*string, bool) {
	if o == nil || o.Channel == nil {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *CFPaymentsEntityCardPayment) HasChannel() bool {
	if o != nil && o.Channel != nil {
		return true
	}

	return false
}

// SetChannel gets a reference to the given string and assigns it to the Channel field.
func (o *CFPaymentsEntityCardPayment) SetChannel(v string) {
	o.Channel = &v
}

// GetCardNumber returns the CardNumber field value if set, zero value otherwise.
func (o *CFPaymentsEntityCardPayment) GetCardNumber() string {
	if o == nil || o.CardNumber == nil {
		var ret string
		return ret
	}
	return *o.CardNumber
}

// GetCardNumberOk returns a tuple with the CardNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CFPaymentsEntityCardPayment) GetCardNumberOk() (*string, bool) {
	if o == nil || o.CardNumber == nil {
		return nil, false
	}
	return o.CardNumber, true
}

// HasCardNumber returns a boolean if a field has been set.
func (o *CFPaymentsEntityCardPayment) HasCardNumber() bool {
	if o != nil && o.CardNumber != nil {
		return true
	}

	return false
}

// SetCardNumber gets a reference to the given string and assigns it to the CardNumber field.
func (o *CFPaymentsEntityCardPayment) SetCardNumber(v string) {
	o.CardNumber = &v
}

// GetCardNetwork returns the CardNetwork field value if set, zero value otherwise.
func (o *CFPaymentsEntityCardPayment) GetCardNetwork() string {
	if o == nil || o.CardNetwork == nil {
		var ret string
		return ret
	}
	return *o.CardNetwork
}

// GetCardNetworkOk returns a tuple with the CardNetwork field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CFPaymentsEntityCardPayment) GetCardNetworkOk() (*string, bool) {
	if o == nil || o.CardNetwork == nil {
		return nil, false
	}
	return o.CardNetwork, true
}

// HasCardNetwork returns a boolean if a field has been set.
func (o *CFPaymentsEntityCardPayment) HasCardNetwork() bool {
	if o != nil && o.CardNetwork != nil {
		return true
	}

	return false
}

// SetCardNetwork gets a reference to the given string and assigns it to the CardNetwork field.
func (o *CFPaymentsEntityCardPayment) SetCardNetwork(v string) {
	o.CardNetwork = &v
}

// GetCardType returns the CardType field value if set, zero value otherwise.
func (o *CFPaymentsEntityCardPayment) GetCardType() string {
	if o == nil || o.CardType == nil {
		var ret string
		return ret
	}
	return *o.CardType
}

// GetCardTypeOk returns a tuple with the CardType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CFPaymentsEntityCardPayment) GetCardTypeOk() (*string, bool) {
	if o == nil || o.CardType == nil {
		return nil, false
	}
	return o.CardType, true
}

// HasCardType returns a boolean if a field has been set.
func (o *CFPaymentsEntityCardPayment) HasCardType() bool {
	if o != nil && o.CardType != nil {
		return true
	}

	return false
}

// SetCardType gets a reference to the given string and assigns it to the CardType field.
func (o *CFPaymentsEntityCardPayment) SetCardType(v string) {
	o.CardType = &v
}

// GetCardCountry returns the CardCountry field value if set, zero value otherwise.
func (o *CFPaymentsEntityCardPayment) GetCardCountry() string {
	if o == nil || o.CardCountry == nil {
		var ret string
		return ret
	}
	return *o.CardCountry
}

// GetCardCountryOk returns a tuple with the CardCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CFPaymentsEntityCardPayment) GetCardCountryOk() (*string, bool) {
	if o == nil || o.CardCountry == nil {
		return nil, false
	}
	return o.CardCountry, true
}

// HasCardCountry returns a boolean if a field has been set.
func (o *CFPaymentsEntityCardPayment) HasCardCountry() bool {
	if o != nil && o.CardCountry != nil {
		return true
	}

	return false
}

// SetCardCountry gets a reference to the given string and assigns it to the CardCountry field.
func (o *CFPaymentsEntityCardPayment) SetCardCountry(v string) {
	o.CardCountry = &v
}

// GetCardBankName returns the CardBankName field value if set, zero value otherwise.
func (o *CFPaymentsEntityCardPayment) GetCardBankName() string {
	if o == nil || o.CardBankName == nil {
		var ret string
		return ret
	}
	return *o.CardBankName
}

// GetCardBankNameOk returns a tuple with the CardBankName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CFPaymentsEntityCardPayment) GetCardBankNameOk() (*string, bool) {
	if o == nil || o.CardBankName == nil {
		return nil, false
	}
	return o.CardBankName, true
}

// HasCardBankName returns a boolean if a field has been set.
func (o *CFPaymentsEntityCardPayment) HasCardBankName() bool {
	if o != nil && o.CardBankName != nil {
		return true
	}

	return false
}

// SetCardBankName gets a reference to the given string and assigns it to the CardBankName field.
func (o *CFPaymentsEntityCardPayment) SetCardBankName(v string) {
	o.CardBankName = &v
}

func (o CFPaymentsEntityCardPayment) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Channel != nil {
		toSerialize["channel"] = o.Channel
	}
	if o.CardNumber != nil {
		toSerialize["card_number"] = o.CardNumber
	}
	if o.CardNetwork != nil {
		toSerialize["card_network"] = o.CardNetwork
	}
	if o.CardType != nil {
		toSerialize["card_type"] = o.CardType
	}
	if o.CardCountry != nil {
		toSerialize["card_country"] = o.CardCountry
	}
	if o.CardBankName != nil {
		toSerialize["card_bank_name"] = o.CardBankName
	}
	return json.Marshal(toSerialize)
}

type NullableCFPaymentsEntityCardPayment struct {
	value *CFPaymentsEntityCardPayment
	isSet bool
}

func (v NullableCFPaymentsEntityCardPayment) Get() *CFPaymentsEntityCardPayment {
	return v.value
}

func (v *NullableCFPaymentsEntityCardPayment) Set(val *CFPaymentsEntityCardPayment) {
	v.value = val
	v.isSet = true
}

func (v NullableCFPaymentsEntityCardPayment) IsSet() bool {
	return v.isSet
}

func (v *NullableCFPaymentsEntityCardPayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCFPaymentsEntityCardPayment(val *CFPaymentsEntityCardPayment) *NullableCFPaymentsEntityCardPayment {
	return &NullableCFPaymentsEntityCardPayment{value: val, isSet: true}
}

func (v NullableCFPaymentsEntityCardPayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCFPaymentsEntityCardPayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


