/*
New Payment Gateway APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2022-01-01
Contact: nextgenapi@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg_sdk_go

import (
	"encoding/json"
)

// CFCryptogram struct for CFCryptogram
type CFCryptogram struct {
	// instrument_id of saved instrument
	InstrumentId *string `json:"instrument_id,omitempty"`
	// TRID issued by card networks
	TokenRequestorId *string `json:"token_requestor_id,omitempty"`
	// token pan number
	CardNumber *string `json:"card_number,omitempty"`
	// token pan expiry month
	CardExpiryMm *string `json:"card_expiry_mm,omitempty"`
	// token pan expiry year
	CardExpiryYy *string `json:"card_expiry_yy,omitempty"`
	// cryptogram
	Cryptogram *string `json:"cryptogram,omitempty"`
	// last 4 digits of original card number
	CardDisplay *string `json:"card_display,omitempty"`
}

// NewCFCryptogram instantiates a new CFCryptogram object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCFCryptogram() *CFCryptogram {
	this := CFCryptogram{}
	return &this
}

// NewCFCryptogramWithDefaults instantiates a new CFCryptogram object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCFCryptogramWithDefaults() *CFCryptogram {
	this := CFCryptogram{}
	return &this
}

// GetInstrumentId returns the InstrumentId field value if set, zero value otherwise.
func (o *CFCryptogram) GetInstrumentId() string {
	if o == nil || o.InstrumentId == nil {
		var ret string
		return ret
	}
	return *o.InstrumentId
}

// GetInstrumentIdOk returns a tuple with the InstrumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CFCryptogram) GetInstrumentIdOk() (*string, bool) {
	if o == nil || o.InstrumentId == nil {
		return nil, false
	}
	return o.InstrumentId, true
}

// HasInstrumentId returns a boolean if a field has been set.
func (o *CFCryptogram) HasInstrumentId() bool {
	if o != nil && o.InstrumentId != nil {
		return true
	}

	return false
}

// SetInstrumentId gets a reference to the given string and assigns it to the InstrumentId field.
func (o *CFCryptogram) SetInstrumentId(v string) {
	o.InstrumentId = &v
}

// GetTokenRequestorId returns the TokenRequestorId field value if set, zero value otherwise.
func (o *CFCryptogram) GetTokenRequestorId() string {
	if o == nil || o.TokenRequestorId == nil {
		var ret string
		return ret
	}
	return *o.TokenRequestorId
}

// GetTokenRequestorIdOk returns a tuple with the TokenRequestorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CFCryptogram) GetTokenRequestorIdOk() (*string, bool) {
	if o == nil || o.TokenRequestorId == nil {
		return nil, false
	}
	return o.TokenRequestorId, true
}

// HasTokenRequestorId returns a boolean if a field has been set.
func (o *CFCryptogram) HasTokenRequestorId() bool {
	if o != nil && o.TokenRequestorId != nil {
		return true
	}

	return false
}

// SetTokenRequestorId gets a reference to the given string and assigns it to the TokenRequestorId field.
func (o *CFCryptogram) SetTokenRequestorId(v string) {
	o.TokenRequestorId = &v
}

// GetCardNumber returns the CardNumber field value if set, zero value otherwise.
func (o *CFCryptogram) GetCardNumber() string {
	if o == nil || o.CardNumber == nil {
		var ret string
		return ret
	}
	return *o.CardNumber
}

// GetCardNumberOk returns a tuple with the CardNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CFCryptogram) GetCardNumberOk() (*string, bool) {
	if o == nil || o.CardNumber == nil {
		return nil, false
	}
	return o.CardNumber, true
}

// HasCardNumber returns a boolean if a field has been set.
func (o *CFCryptogram) HasCardNumber() bool {
	if o != nil && o.CardNumber != nil {
		return true
	}

	return false
}

// SetCardNumber gets a reference to the given string and assigns it to the CardNumber field.
func (o *CFCryptogram) SetCardNumber(v string) {
	o.CardNumber = &v
}

// GetCardExpiryMm returns the CardExpiryMm field value if set, zero value otherwise.
func (o *CFCryptogram) GetCardExpiryMm() string {
	if o == nil || o.CardExpiryMm == nil {
		var ret string
		return ret
	}
	return *o.CardExpiryMm
}

// GetCardExpiryMmOk returns a tuple with the CardExpiryMm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CFCryptogram) GetCardExpiryMmOk() (*string, bool) {
	if o == nil || o.CardExpiryMm == nil {
		return nil, false
	}
	return o.CardExpiryMm, true
}

// HasCardExpiryMm returns a boolean if a field has been set.
func (o *CFCryptogram) HasCardExpiryMm() bool {
	if o != nil && o.CardExpiryMm != nil {
		return true
	}

	return false
}

// SetCardExpiryMm gets a reference to the given string and assigns it to the CardExpiryMm field.
func (o *CFCryptogram) SetCardExpiryMm(v string) {
	o.CardExpiryMm = &v
}

// GetCardExpiryYy returns the CardExpiryYy field value if set, zero value otherwise.
func (o *CFCryptogram) GetCardExpiryYy() string {
	if o == nil || o.CardExpiryYy == nil {
		var ret string
		return ret
	}
	return *o.CardExpiryYy
}

// GetCardExpiryYyOk returns a tuple with the CardExpiryYy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CFCryptogram) GetCardExpiryYyOk() (*string, bool) {
	if o == nil || o.CardExpiryYy == nil {
		return nil, false
	}
	return o.CardExpiryYy, true
}

// HasCardExpiryYy returns a boolean if a field has been set.
func (o *CFCryptogram) HasCardExpiryYy() bool {
	if o != nil && o.CardExpiryYy != nil {
		return true
	}

	return false
}

// SetCardExpiryYy gets a reference to the given string and assigns it to the CardExpiryYy field.
func (o *CFCryptogram) SetCardExpiryYy(v string) {
	o.CardExpiryYy = &v
}

// GetCryptogram returns the Cryptogram field value if set, zero value otherwise.
func (o *CFCryptogram) GetCryptogram() string {
	if o == nil || o.Cryptogram == nil {
		var ret string
		return ret
	}
	return *o.Cryptogram
}

// GetCryptogramOk returns a tuple with the Cryptogram field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CFCryptogram) GetCryptogramOk() (*string, bool) {
	if o == nil || o.Cryptogram == nil {
		return nil, false
	}
	return o.Cryptogram, true
}

// HasCryptogram returns a boolean if a field has been set.
func (o *CFCryptogram) HasCryptogram() bool {
	if o != nil && o.Cryptogram != nil {
		return true
	}

	return false
}

// SetCryptogram gets a reference to the given string and assigns it to the Cryptogram field.
func (o *CFCryptogram) SetCryptogram(v string) {
	o.Cryptogram = &v
}

// GetCardDisplay returns the CardDisplay field value if set, zero value otherwise.
func (o *CFCryptogram) GetCardDisplay() string {
	if o == nil || o.CardDisplay == nil {
		var ret string
		return ret
	}
	return *o.CardDisplay
}

// GetCardDisplayOk returns a tuple with the CardDisplay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CFCryptogram) GetCardDisplayOk() (*string, bool) {
	if o == nil || o.CardDisplay == nil {
		return nil, false
	}
	return o.CardDisplay, true
}

// HasCardDisplay returns a boolean if a field has been set.
func (o *CFCryptogram) HasCardDisplay() bool {
	if o != nil && o.CardDisplay != nil {
		return true
	}

	return false
}

// SetCardDisplay gets a reference to the given string and assigns it to the CardDisplay field.
func (o *CFCryptogram) SetCardDisplay(v string) {
	o.CardDisplay = &v
}

func (o CFCryptogram) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.InstrumentId != nil {
		toSerialize["instrument_id"] = o.InstrumentId
	}
	if o.TokenRequestorId != nil {
		toSerialize["token_requestor_id"] = o.TokenRequestorId
	}
	if o.CardNumber != nil {
		toSerialize["card_number"] = o.CardNumber
	}
	if o.CardExpiryMm != nil {
		toSerialize["card_expiry_mm"] = o.CardExpiryMm
	}
	if o.CardExpiryYy != nil {
		toSerialize["card_expiry_yy"] = o.CardExpiryYy
	}
	if o.Cryptogram != nil {
		toSerialize["cryptogram"] = o.Cryptogram
	}
	if o.CardDisplay != nil {
		toSerialize["card_display"] = o.CardDisplay
	}
	return json.Marshal(toSerialize)
}

type NullableCFCryptogram struct {
	value *CFCryptogram
	isSet bool
}

func (v NullableCFCryptogram) Get() *CFCryptogram {
	return v.value
}

func (v *NullableCFCryptogram) Set(val *CFCryptogram) {
	v.value = val
	v.isSet = true
}

func (v NullableCFCryptogram) IsSet() bool {
	return v.isSet
}

func (v *NullableCFCryptogram) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCFCryptogram(val *CFCryptogram) *NullableCFCryptogram {
	return &NullableCFCryptogram{value: val, isSet: true}
}

func (v NullableCFCryptogram) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCFCryptogram) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


