/*
New Payment Gateway APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2022-01-01
Contact: nextgenapi@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_pg_sdk_go

import (
	"encoding/json"
)

// CFPaylater struct for CFPaylater
type CFPaylater struct {
	// The channel for cardless EMI is always `link`
	Channel string `json:"channel"`
	// One of [\"kotak\", \"flexipay\", \"zestmoney\", \"lazypay\", \"olapostpaid\"]. Please note that Flexipay is offered by HDFC bank
	Provider string `json:"provider"`
	// Customers phone number for this payment instrument. If the customer is not eligible you will receive a 400 error with type as 'invalid_request_error' and code as 'invalid_request_error'
	Phone string `json:"phone"`
}

// NewCFPaylater instantiates a new CFPaylater object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCFPaylater(channel string, provider string, phone string) *CFPaylater {
	this := CFPaylater{}
	this.Channel = channel
	this.Provider = provider
	this.Phone = phone
	return &this
}

// NewCFPaylaterWithDefaults instantiates a new CFPaylater object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCFPaylaterWithDefaults() *CFPaylater {
	this := CFPaylater{}
	return &this
}

// GetChannel returns the Channel field value
func (o *CFPaylater) GetChannel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *CFPaylater) GetChannelOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *CFPaylater) SetChannel(v string) {
	o.Channel = v
}

// GetProvider returns the Provider field value
func (o *CFPaylater) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *CFPaylater) GetProviderOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *CFPaylater) SetProvider(v string) {
	o.Provider = v
}

// GetPhone returns the Phone field value
func (o *CFPaylater) GetPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *CFPaylater) GetPhoneOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *CFPaylater) SetPhone(v string) {
	o.Phone = v
}

func (o CFPaylater) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["channel"] = o.Channel
	}
	if true {
		toSerialize["provider"] = o.Provider
	}
	if true {
		toSerialize["phone"] = o.Phone
	}
	return json.Marshal(toSerialize)
}

type NullableCFPaylater struct {
	value *CFPaylater
	isSet bool
}

func (v NullableCFPaylater) Get() *CFPaylater {
	return v.value
}

func (v *NullableCFPaylater) Set(val *CFPaylater) {
	v.value = val
	v.isSet = true
}

func (v NullableCFPaylater) IsSet() bool {
	return v.isSet
}

func (v *NullableCFPaylater) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCFPaylater(val *CFPaylater) *NullableCFPaylater {
	return &NullableCFPaylater{value: val, isSet: true}
}

func (v NullableCFPaylater) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCFPaylater) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


